### ISSUE TITLE
Remove the links with placeholders and sync the placeholder text

### ISSUE THREAD

**Issue by cknabe** [IBM-Bluemix-Docs/tutorials#1]
![image](https://user-images.githubusercontent.com/13582620/32619573-c9b66062-c540-11e7-8157-5fd4d8c15447.png)
The link to http://YourPublicIPAddress/info.php should not be a real link. I'm unsure if the placeholder text should be something else or not?

![image](https://user-images.githubusercontent.com/13582620/32619635-f5131a8e-c540-11e7-9d13-d8d60b810b67.png)
Same for this link ^

The two links should also be using the same place-holder text.

**Comment by VidyasagarMSC** [comment]
Fixed it and should be available in the next drop.
