### ISSUE TITLE
Mixed COS references in infrastructure-as-code-terraform

### ISSUE THREAD

**Issue by davetropeano** [IBM-Bluemix-Docs/tutorials#11]
The terraform code in `infrastructure-as-code` references Swift based object storage:

```
resource "ibm_object_storage_account" "lamp_storage" {
  count = "${var.object_storage_enabled}"
}

variable "object_storage_enabled" {
    default = 1
}
```

But the links and screen shots seem to refer to our newer COS offering which would be instantiate using `service_instance` since it is an IBM Cloud catalog entry

**Comment by davetropeano** [comment]
Also, in the *Products* list the link to `Terraform` goes to IBM Cloud Schematics which has been deprecated

**Comment by Twanawebtech** [comment]
@davetropeano all items are resolved. The solution is fully updated to use the IBM Cloud Object Storage and not the Swift version. This can be viewed on staging and soon be in production. 
Please close this issue.
