### ISSUE TITLE
Typos in text

### ISSUE THREAD

**Issue by johnholtman** [IBM-Bluemix-Docs/tutorials#12]
Two bullet points in the list of "many reasons why you would use a Content Delivery Network" have typos:

- 1st bullet:  "only it is not available in its cache" _should be_ "only **if** it is not available in its cache"

- 3rd bullet: "different domain that your main application" _should be_ "different domain **than** your main application"

**Comment by rvennam** [comment]
Thanks! Changes will be rolled out soon.
