### ISSUE TITLE
Add spark service

### ISSUE THREAD

**Issue by Ronanb3** [IBM-Bluemix-Docs/tutorials#13]
I followed the instruction but I didn't have a spark engine. I had to add a spark service in the settings of the project and associate it with my project.
Then I can create a Notebook with a spark engine.

**Comment by l2fprod** [comment]
@Ronanb3 what tutorial were you going through?

**Comment by VidyasagarMSC** [comment]
@Ronanb3 Is this in the Spark tutorial??

**Comment by VidyasagarMSC** [comment]
@l2fprod By repeatedly reading the issue description. I sense it is IoT + Machine Learning Tutorial. As the fix is in place. Closing this for now.

@Ronanb3 Please feel free to re-open if you think there's something missing.
