### ISSUE TITLE
can not downlod csv (big-data-analytics-spark.md)

### ISSUE THREAD

**Issue by ebisennet** [IBM-Bluemix-Docs/tutorials#14]
The following downloads can not be performed

https://github.com/IBM-Bluemix-Docs/tutorials/blob/master/big-data-analytics-spark.md#load-data

```
# Load data

Next load three open data sets and make them available within the notebook. The Pixiedust library allows you to easily load `CSV files using an URL.`
```

**Comment by l2fprod** [comment]
The correct link is https://pixiedust.github.io/pixiedust/loaddata.html

It will be fixed in our next drop
