### ISSUE TITLE
"Gather, visualize, and analyze IoT data" no longer works

### ISSUE THREAD

**Issue by Harald-U** [IBM-Bluemix-Docs/tutorials#16]
Due to changes in Watson Studio the tutorial no longer works, at least not for me.
Problems are in Topic "Detect Anomalies using Machine Learning"

Just annoying is section "Create a new project"
Step 3 is different now, only 5 options, none of which is Jupyter Notebook. Closest seems Data Science

But this step no longer works: "Create a Jupyter (ipynb) notebook"

Step 1 -- No longer need to create a Spark instance, can't select it later

Instead I did the following:

1. Create a Data Science Project
2. Add Cloudant Connection
3. "New Notebook" --> This creates a Python 3.5 runtime, no option to select existing Spark instance
4. Starting from Step 4, Import the notebook from URL then run it fails in [1]
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8ae0609ffea6> in <module>()
      2 import pixiedust
      3 # Use play-json version 2.5.9. Latest version is not supported at this time.
----> 4 pixiedust.installPackage("com.typesafe.play:play-json_2.11:2.5.9")
      5 # Get the latest sql-cloudant library
      6 pixiedust.installPackage("org.apache.bahir:spark-sql-cloudant_2.11:0")

AttributeError: module 'pixiedust' has no attribute 'installPackage'

**Comment by Harald-U** [comment]
I reran the tutorial "Gather, visualize, and analyze IoT data" and it basically now runs.
Two things are missing in the description in section "Create a Jupyter (ipynb) notebook"
1. After creating the Spark Instance you have to add the instance to the Project Settings otherwise you can't select it as runtime in (5)
2. After opening the Jupyter Notebook and loading the sample notebook from the URL, I get a popup "Kernel not found" where I can select a matching Kernel. I selected "Python 2 with Spark 2.1" but it is not clear if this is the correct value or if the Python version doesn't matter.
With these settings I could complete the tutorial.

**Comment by VidyasagarMSC** [comment]
@Harald-U Thanks for pointing the issue. All the changes are pushed to staging and should be available in production soon. Closing the issue for now.

**Comment by dermotwalsh** [comment]
@Harald-U I'm trying to get this IoT tutorial to run and I'm hitting the same issue as you. I get an error:
```
Py4JJavaError: An error occurred while calling o98.load.
: java.lang.NoSuchMethodError: org/apache/spark/sql/DataFrameReader.json(Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/Dataset; (loaded from file:/usr/local/src/spark21master/spark-2.1.3-bin-2.7.3/jars/spark-sql_2.11-2.1.3.jar by sun.misc.Launcher$AppClassLoader@1e4ae355) called from class org.apache.bahir.cloudant.DefaultSource (loaded from file:/gpfs/global_fs01/cluster/yp-spark-lon02-env5-0101.bluemix.net/user/s12f-5ca88b3c610670-084a778c5526/data/libs/spark-sql-cloudant_2.11-2.2.2.jar by sun.misc.Launcher$AppClassLoader@1e4ae355).
```
I have added the spark I created via the project settings, and I am using `Python 2 Spark 2.1`.
Are you still able to run this tutorial end-2-end?

**Comment by Harald-U** [comment]
@dermotwalsh This has been a while but reading my notes above I seem to have been able to complete the tutorial . Haven't tried it in a while and currently don't have time to do it.
