### ISSUE TITLE
Pricing Calculator Issue

### ISSUE THREAD

**Issue by briansay** [IBM-Bluemix-Docs/tutorials#17]
Hi. you state in the readme under services required as VRA. Then you state this may incur a cost, please use pricing calculator to check the cost. However the pricing calculator doesn't show VRA's? 

This is quite misleading?

**Comment by nicolasmendoza** [comment]
+1

**Comment by l2fprod** [comment]
thanks for the feedback. Indeed VRA is missing from there. An issue has been raised. In the meantime, the link to the pricing calculator has been removed for this tutorial to avoid the confusion.
