### ISSUE TITLE
Geographical Load Balancing and Failover

### ISSUE THREAD

**Issue by nheidloff** [IBM-Bluemix-Docs/tutorials#2]
How can you do geographical load balancing and failover? My understanding is that you need a third party service, for example dyn.com, at this point. Or does the IBM Cloud have a service to do this?

Does it make sense to clarify this in the title and/or description of the tutorial? When I read the title I was expecting geographical failover as mentioned here: https://www.ibm.com/developerworks/cloud/library/cl-multi-region-bluemix-apps-with-cloudant-and-dyn-trs/index.html

**Comment by rvennam** [comment]
Thanks for the feedback! We will address this.
