### ISSUE TITLE
changing from username and password to IAM API keys

### ISSUE THREAD

**Issue by Fe1ix789** [IBM-Bluemix-Docs/tutorials#20]
Since the authentication method has changed, I am not able to get the tutorial running as there is no username and password combination anymore for the STT or TTS anymore.

(Step 3 of "Configure and Run the Android App")

Here is the link to the change.
https://console.bluemix.net/docs/services/speech-to-text/getting-started.html#getting-started-tutorial

**Comment by l2fprod** [comment]
@Fe1ix789 

we just committed a change for https://console.bluemix.net/docs/tutorials/android-watson-chatbot.html#build-a-voice-enabled-android-chatbot to use the API key and other updates in Watson Assistant. The page should get updated later today.
