### ISSUE TITLE
About error : Unable to query services of the target resource group

### ISSUE THREAD

**Issue by Ocean5app** [IBM-Bluemix-Docs/tutorials#24]
I did everything as tutorial, when I submit "sh setup.sh", it return a message like below

error: Unable to query services of the target resource group '2cb459e61930497894ac83785586927b':
 Get https://resource-controller.ibm.com/v1/resource_instances?resource_group_id=2cb459e61930497894ac83785586927b&resource_id=&resource_plan_id=: dial tcp: lookup resource-controller.ibm.com: no such host

it is like the step [created action slackdemo/db2Setup] has something wrong, what should I do to fix this problem?

**Comment by l2fprod** [comment]
@data-henrik any clue?

**Comment by data-henrik** [comment]
@Ocean5app Are you referring to https://github.com/IBM-Cloud/slack-chatbot-database-watson/blob/master/setup.sh? Is it still a problem? It looks like a transient problem with either DNS or service availability.

If it is still a problem:
Which region are you using? What does `ibmcloud fn package list` return?

**Comment by data-henrik** [comment]
seems like it has been resolved
