### ISSUE TITLE
Kubernetes Deployment issue - Asynchronous data processing using object storage and pub/sub messaging

### ISSUE THREAD

**Issue by shankarjai2525** [IBM-Bluemix-Docs/tutorials#25]
Unable to deploy the tutorial java worker pod. I'm getting this error

container "pubsubworker" in pod "pubsubworker-deployment-7b598fb7d7-dhtx8" is waiting to start: CreateContainerConfigError

**Comment by l2fprod** [comment]
@shankarjai2525 

I went through the tutorial and did not encounter the issue

1/ can you check that the secrets binding-mymessagehub and binding-myobjectstorage exist with `kubectl get secrets`?
2/ `kubectl get pod pubsubworker-deployment-7b598fb7d7-dhtx8` may also give more information about why the pod is not starting

**Comment by l2fprod** [comment]
please reopen if you still encounter an issue
