### ISSUE TITLE
VPC PGW limits

### ISSUE THREAD

**Issue by nostromo200** [IBM-Bluemix-Docs/tutorials#26]
VPC currently stated as having a limit of one PGW per zone. Also the assignment of floating IP to a VSI is not related to whether there is a public gateway attached to the subnet

**Comment by VidyasagarMSC** [comment]
@nostromo200 Based on your email communication, can you close this issue for now?

**Comment by VidyasagarMSC** [comment]
@nostromo200 @l2fprod Here's what I tried based on our discussion over Slack

- Detached the PGW on the subnet
- Tried pinging the VSI via the floating IP and the ping is successful
- Also, after SSHing into the server, tried running updates and it worked.

**Comment by l2fprod** [comment]
next doc update will only enable public gateway where needed. Subnets with VSIs having floating IPs will not require a public gateway attached.
