### ISSUE TITLE
CNAMES ISSUES

### ISSUE THREAD

**Issue by vickoman** [IBM-Bluemix-Docs/tutorials#3]
Very helpfull, but i have a question, based in this article we have 1 app deployed in two regions US-south and UK, Also is my scenario with my personal app, but in the step when your set the CNAME only set cname for US-south, how Bluemix know from which Region attend the request?

**Comment by rvennam** [comment]
Thanks for raising this issue. Our team will review this and post an update shortly.

**Comment by rvennam** [comment]
Currently, the doc outlines a manual active-passive setup where the second region is ready to handle requests if the DNS is manually changed to point to it. Global load balancers and traffic management services could be used to automate this. 

The doc has been updated to make this more clear.
