### ISSUE TITLE
Secure web application across multiple regions issue

### ISSUE THREAD

**Issue by csulrong** [IBM-Bluemix-Docs/tutorials#31]
In the tutorial `Secure web application across multiple regions` (tutorials/multi-region-webapp.md), when using `<your_app>.mybluemix.net` for CIS origin server, will have issue for HTTPS access to cloud foundry apps when their apps are associated to custom domain. 

In case of added custom routes to their CF application, customer has the following options to configure their origin servers for CIS:
- Use `secure.<region>.bluemix.net` if their cf apps having the route `<custom-domain>.<region>.mybluemix.net`, where `<region>` can be `us-south`, `us-east`, `eu-gb`, `eu-de`, `au-syd`.
- Use `<custom-domain>.<region>.cf.cloud.ibm.com` if their cf apps having this style of route.
- Use `<custom-domain>.<region>.cf.appdomain.cloud` if their cf apps having this style of route.

Here is the link for the custom domain: https://cloud.ibm.com/docs/apps?topic=creating-apps-updatingapps#mapcustomdomain

**Comment by l2fprod** [comment]
thank you.

I've added a note about alternative domains, pointing to the doc link.

It will be available in our next doc drop.
