### ISSUE TITLE
Scalable web application on Kubernetes

### ISSUE THREAD

**Issue by rajeshchala** [IBM-Bluemix-Docs/tutorials#32]
after creating a started app and creating a docker image, creting an instance and testing http://localhost:9080/<nameofproject> ( replaced with app name) doesnt work. it always says Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /myapp

**Comment by l2fprod** [comment]
@rajeshchala 

please try http://localhost:9080/  directly without the app name. The "dev" plugin no longer needs the app name. Tutorial will be updated. Thank you for the report.
