### ISSUE TITLE
Latest READ.me not displaying correctly

### ISSUE THREAD

**Issue by ANDRESROMEROH** [IBM-Bluemix-Docs/tutorials#36]
There are several points in the new READ.me not displaying correctly, you can find elements showing up as "{:new_window: target="_blank"}" or similar.

**Comment by data-henrik** [comment]
@ANDRESROMEROH which READ.me or document are you referring to?

**Comment by ANDRESROMEROH** [comment]
@data-henrik sorry I forgot to attach the URL... It is https://github.com/IBM-Bluemix-Docs/tutorials/blob/master/mean-stack.md

**Comment by data-henrik** [comment]
That is the source for https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-mean-stack which displays well for me. The Markdown sources for all IBM Cloud documentation is here on GitHub to allow PRs.

**Comment by ANDRESROMEROH** [comment]
Okay, I can see the instructions from that link. Thank you! We can dismiss this issue.
