### ISSUE TITLE
JOB4 got error : ValueError: time data '2018-03-11T23:10:31.298+08:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by owhc** [IBM-Bluemix-Docs/tutorials#4]
Executed below part, got the error message in JOB4:
ValueError: time data '2018-03-11T23:10:31.298+08:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

`# This function converts the string cell into a timestamp type:
str_to_ts =  udf (lambda d: datetime.strptime(d, "%Y-%m-%dT%H:%M:%S.%fZ"), TimestampType())

sparkDf = cloudantdata.selectExpr("value.deviceId as deviceId", "value.deviceType as deviceType", "value.eventType as eventType" ,  "value.timestamp as timestamp", "value.data.*","value.data.d.oa as oa","value.data.d.ob as ob","value.data.d.og as og")
sparkDf = sparkDf.withColumn('ts', str_to_ts(col('timestamp')))
sparkDf.cache()
sparkDf.createOrReplaceTempView("deviceData")

# show the resulting schema and data 
sparkDf.printSchema()
spark.sql("SELECT * from deviceData").show(10)`

**Comment by owhc** [comment]
That is not an issue. I checked the code. I realized that Historical date was collecting in +8 timezone. So that's why.

**Comment by l2fprod** [comment]
^ @VidyasagarMSC

**Comment by VidyasagarMSC** [comment]
Closing this as there's no change required.
