### ISSUE TITLE
Incorrect tip re: space for clusters

### ISSUE THREAD

**Issue by bhpratt** [IBM-Bluemix-Docs/tutorials#5]
https://console.bluemix.net/docs/tutorials/users-teams-applications.html#objectives

`Before you create a cluster, either through the IBM Cloud UI or through the command line, you must log into a specific IBM Cloud region, account, organization, and space. The space where you are logged in is the space where logging and monitoring data for the cluster and its resources is collected. If later you want to change the space where a cluster is sending its logging data, you can use the logging plugin for the bx command line.`

This section is incorrect. Cluster has no association with spaces. Monitoring works at the account level and logs are space or account, depending on what is selected by the user. Recommend deleting this tip.

**Comment by l2fprod** [comment]
Replaced the tip with instructions to use the "Enable Logging" action in the UI
