### ISSUE TITLE
Add estimated time of completion

### ISSUE THREAD

**Issue by BryanWoo** [IBM-Bluemix-Docs/tutorials#7]
It's better to declare the estimated time of completion for the whole tutorial and each section.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2917463/37500720-10192606-2906-11e8-899c-4b035eba848a.png">

**Comment by rvennam** [comment]
Thanks for the feedback. 

In the past, we determined that the completion time varies too much between every user. We will consider revisiting this topic.
